name: hafiz_test
description: Master the Quran, One Ayah at a Time

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 25.12.23+15

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  path: ^1.9.0
  sqflite: ^2.4.1
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.15
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.5
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  marquee: ^2.3.0
  audio_video_progress_bar: ^2.0.3
  showcaseview: ^4.0.1
  scrollable_positioned_list: ^0.3.8
  get_it: ^8.1.0
  in_app_review: ^2.0.9
  mixpanel_flutter: ^2.4.4
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

  sqlite3: ^2.4.7

  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/
    - assets/img/onboarding/
    - assets/quran-offline.sqlite
    - shorebird.yaml

  fonts:
    - family: Kitab
      fonts:
        - asset: assets/fonts/Kitab-Bold.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
